name: Spark-Config CI
run-name: Spark Config CI
on:
    push:
        branches: main
    pull_request:
        branches:
            - main
            - develop
jobs:
  Spark-Config-CI:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.10", "3.13"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            path: config_repo
            submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre-commit
        run: pip install pre-commit && cd ${{ github.workspace }}/config_repo && pre-commit run --all-files
      - name: Install Spark Config
        run: cd ${{ github.workspace }}/config_repo && pwd && pip install .
      - name: Run test script
        run: cd ${{ github.workspace }}/config_repo && pytest
      - run: echo "🍏 This job's status is ${{ job.status }}."
